# Generated by Django 5.2.12 on 2026-03-31 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('phone', models.CharField(max_length=17)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('latitude', models.FloatField(blank=True, help_text='Latitude from postcode', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude from postcode', null=True)),
                ('coordinates_updated_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information volunteers should know')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname', 'forename'],
            },
        ),
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Preferred gender of volunteer (leave blank for no preference)', max_length=1)),
                ('preferred_languages', models.JSONField(default=list, help_text='List of preferred languages for communication')),
                ('preferred_days', models.JSONField(default=list, help_text='List of preferred days for visits')),
                ('preferred_times', models.JSONField(default=list, help_text='List of preferred time slots')),
                ('preferred_location', models.CharField(blank=True, help_text='Preferred meeting location (if different from home address)', max_length=255)),
                ('preferred_tasks', models.JSONField(default=list, help_text='List of tasks client needs assistance with')),
                ('has_pets', models.BooleanField(blank=True, help_text='Whether the client has pets in their home', null=True)),
                ('availability_notes', models.TextField(blank=True, help_text='Any specific availability notes or restrictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='client.clientprofile')),
            ],
            options={
                'verbose_name_plural': 'Client preferences',
            },
        ),
    ]
