# Generated by Django 5.2.12 on 2026-04-14 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUGGESTED', 'Client Sent Request'), ('ACCEPTED', 'Both Accepted'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('compatibility_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('matching_notes', models.TextField(blank=True)),
                ('client_accepted', models.BooleanField(default=False)),
                ('client_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer_accepted', models.BooleanField(default=False)),
                ('volunteer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_client', to='client.clientprofile')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_volunteer', to='volunteer.volunteerprofile')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'unique_together': {('client', 'volunteer')},
            },
        ),
    ]
