# Generated by Django 5.2.12 on 2026-04-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('latitude', models.FloatField(blank=True, help_text='Latitude from postcode', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude from postcode', null=True)),
                ('coordinates_updated_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='volunteer_photos/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself and why you want to volunteer')),
                ('skills_description', models.TextField(blank=True, help_text='Describe your relevant skills and experience')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname', 'forename'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Preferred gender of client (leave blank for no preference)', max_length=1)),
                ('preferred_languages', models.JSONField(default=list, help_text='List of languages you can communicate in')),
                ('preferred_days', models.JSONField(default=list, help_text="List of days you're available")),
                ('preferred_times', models.JSONField(default=list, help_text="List of time slots you're available")),
                ('preferred_tasks', models.JSONField(default=list, help_text="List of tasks you're willing to help with")),
                ('can_work_with_pets', models.BooleanField(default=False)),
                ('has_transportation', models.BooleanField(default=False)),
                ('availability_notes', models.TextField(blank=True, help_text='Any specific availability notes or restrictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='volunteer.volunteerprofile')),
            ],
            options={
                'verbose_name_plural': 'Volunteer preferences',
            },
        ),
    ]
